In [5]:
a = [1.0, 2.0, 1.0]

In [6]:
import torch

a = torch.ones(3)
a

tensor([1., 1., 1.])

In [7]:
a[1]

tensor(1.)

In [8]:
float(a[1])

1.0

In [9]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [10]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points[1:])
print(points[1:, :])
print(points[1:, 0])
print(points[None])

tensor([[5., 3.],
        [2., 1.]])
tensor([[5., 3.],
        [2., 1.]])
tensor([5., 2.])
tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])


In [14]:
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])
batch_t = torch.randn(2, 3, 5, 5)
img_t.shape, batch_t.shape

(torch.Size([3, 5, 5]), torch.Size([2, 3, 5, 5]))

In [15]:
img_gray_native = img_t.mean(-3)
batch_gray_native = batch_t.mean(-3)
img_gray_native.shape, batch_gray_native.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))